linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - govet
    - ineffassign
    - gosimple
    - staticcheck
    - unused
    - misspell
    - unconvert
  enable-all: false
run:
  timeout: 20m
issues:
  exclude-dirs:
    - integrationtests
