version: "3"

tasks:
    submodules:
        desc: download submodules
        cmds:
            - git submodule init
            - git submodule update

    build-dev:
        desc: Build dev
        cmds:
            - go get
            - go mod tidy
            - mkdir -p ~/.terraform.d/plugins/threefoldtechdev.com/providers/grid/0.2/linux_amd64/
            - go build -o terraform-provider-grid
            - mv terraform-provider-grid ~/.terraform.d/plugins/threefoldtechdev.com/providers/grid/0.2/linux_amd64/

    docs:
        desc: generate docs
        cmds:
            - go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs

    testacc:
        desc: test
        cmds:
            - TF_ACC=1 go test ./... -v $(TESTARGS) -timeout 120m
