name: terraform-provider-grid-basic

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
          TWIN_ID: ${{ secrets.TWIN_ID }}
          MNEMONICS: ${{ secrets.MNEMONICS }}
      run: go test -v ./...
